# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cf1411b1-60b3-4a6d-ba60-d988271efb75";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/333C-CCF7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    fileSystems."/mnt/hdd1" = {
  device = "/dev/disk/by-uuid/3282F99F2048D3B1";
  fsType = "ntfs";
  options = [
    "rw"
    "uid=1000"
    "gid=100"
    "nofail"
    "x-systemd.device-timeout=5s"
  ];
};

fileSystems."/mnt/hdd2" = {
  device = "/dev/disk/by-uuid/42024CB2537A99BB";
  fsType = "ntfs";
  options = [
    "rw"
    "uid=1000"
    "gid=100"
    "nofail"
    "x-systemd.device-timeout=5s"
  ];
};

fileSystems."/mnt/hdd3" = {
  device = "/dev/disk/by-uuid/23F52D3E4CB4A209";
  fsType = "ntfs";
  options = [
    "rw"
    "uid=1000"
    "gid=100"
    "nofail"
    "x-systemd.device-timeout=5s"
  ];
};


  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
